service:
  name: quokka-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DYNAMODB_TABLENAME: 'quokka'
    DYNAMODB_REGION: 'eu-west-2'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:eu-west-2:823663213799:table/quokka'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: 'arn:aws:dynamodb:eu-west-2:823663213799:table/quokka/index/*'

functions:
  app:
    handler: src/handlers/handler.index
    events:
      - http: ANY /
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
      - http: 'ANY {proxy+}'
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
  # getArtistByID:
  #   handler: src/handler.getArtistByID
  #   events:
  #     - http:
  #         method: get
  #         path: getArtistByID/{uuid}
  # getAllArtistsByTeamID:
  #   handler: src/handlers.getAllArtistsByTeamID
  #   events:
  #     - http:
  #         method: get
  #         path: getAllArtistsByTeamID

resources:
  Resources:
    quokkaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quokka
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: N
          - AttributeName: itemType
            AttributeType: S
          - AttributeName: ownerUuid
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: itemtype-ownerUuid-index
            KeySchema:
              - AttributeName: itemType
                KeyType: HASH
              - AttributeName: ownerUuid
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - data
                - artistName
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
